In [8]:
import numpy as np

data = np.array([[1,2,3]])
w = np.array([4,5,6])

print(np.dot(data, w))

# 손실 함수(loss function)
# 예측값 실제값 차이를 나타내는 것

# 예측값을 계산하는 함수(활성화 함수 - activation function)
# 손실이 작게 나오는 웨이트 값 조정 (경사하강)


data = np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9],
  [11, 12, 13],
  [14, 15, 16],
  [17, 18, 19],
  [21, 22, 23],
  [24, 25, 26],
  [27, 28, 29]
])

w = np.array([
  [1, 2, 1, 3],
  [2, 1, 2, 1],
  [1, 3, 1, 2],
])

print(np.dot(data, w))
print("-" * 50)
# print(np.sum(np.dot(data, w)))

# 과적합(Overfitting) 피하기 위해서 일부러 예측이 틀리도록 데이터를 제공
# 차트 그리기 (x축 : 횟수, y축 : 손실량(율))
# google api, naver api



[32]
[[  8  13   8  11]
 [ 20  31  20  29]
 [ 32  49  32  47]
 [ 48  73  48  71]
 [ 60  91  60  89]
 [ 72 109  72 107]
 [ 88 133  88 131]
 [100 151 100 149]
 [112 169 112 167]]
--------------------------------------------------
